[language.c_cpp]
filetypes = ["c", "cpp"]
roots = [".ccls-root", "compile_commands.json"]
command = "ccls"
args = ["--init={\"completion\":{\"detailedLabel\":false},\"compilationDatabaseDirectory\":\"build\"}"]

